    INSERT INTO characters (name) VALUES ('Jon Snow'), 
    ('Robert Baratheon'),
    ('Jaime Lannister'),
    ('Cersei Lannister'),
    ('Sansa Stark'),
    ('Arya Stark'),
    ('Robb Stark'),
    ('Joffrey Baratheon'),
    ('Daenerys Targaryen'),
    ('Tyrion Lannister'),
    ('Brienne of Tarth');